services:
  - type: web
    name: qr-checkin
    env: python
    pythonVersion: "3.12.10"
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
